uploads = []

[[generated]]
id = "7E0EMczyQ0WkGy_zWxpEy"
uri = "file://client/public/images/advisor-portrait.png"
type = "image"
title = "black woman financial advisor portrait"

[[generated]]
id = "-Y_Zakjc4bvdevEIaAW7z"
uri = "file://client/public/images/partners/capricorn.png"
type = "image"
title = "capricorn asset management logo"

[[generated]]
id = "r_BjmSNg-j4XxT7PN_M7D"
uri = "file://client/public/images/pension-fund-groups.png"
type = "image"
title = "group pension fund corporate team"

[[generated]]
id = "gWWaYpihWfQWcJS_rUbxP"
uri = "file://client/public/images/hero-light.png"
type = "image"
title = "soft hero family"

[[generated]]
id = "dieiQNxFsN4YGi9-83r6e"
uri = "file://client/public/images/car-insurance-ad.png"
type = "image"
title = "car insurance ad banner"

[[generated]]
id = "p7-SVNpEuMJE7QEm6acks"
uri = "file://client/public/images/wills-estates.png"
type = "image"
title = "diverse boardroom for Wills and Estates"

[[generated]]
id = "lawHJj7W6Vq6dtpIZZQGe"
uri = "file://client/public/images/medical-aid.png"
type = "image"
title = "medical aid image with diverse doctor and patient"

[[outputs]]
id = "lA5pRpgnXuRkrp3h6lflt"
uri = "file://attached_assets/stock_images/sanlam-logo.jpg"
type = "image"
title = "Sanlam financial services logo white background clean"
